services:
  web-admin:
    image: ghcr.io/aboutnb/gh-asset-center-web:latest
    container_name: web-admin
    restart: unless-stopped
    ports:
      - "18700:18700"
    env_file:
      - ./backend/.env
