import http from './http';

export const login = (payload) => http.post('/admin/auth/login', payload);
export const logout = () => http.post('/admin/auth/logout');
export const fetchCurrentUser = () => http.get('/admin/auth/me');
export const changePassword = (payload) => http.post('/admin/auth/change-password', payload);
export const fetchDashboardSummary = () => http.get('/admin/dashboard/summary');
export const fetchMailAccounts = (params) => http.get('/admin/mail-accounts', { params });
export const importMailAccounts = (payload) => http.post('/admin/mail-accounts/import', payload);
export const createMailAccount = (payload) => http.post('/admin/mail-accounts', payload);
export const updateMailAccount = (id, payload) => http.put(`/admin/mail-accounts/${id}`, payload);
export const deleteMailAccount = (id) => http.delete(`/admin/mail-accounts/${id}`);
export const fetchMailMessages = (id) => http.get(`/admin/mail-accounts/${id}/messages`);
export const bulkUpdateMailStatus = (payload) => http.post('/admin/mail-accounts/bulk-status', payload);
export const bulkDeleteMailAccounts = (payload) => http.post('/admin/mail-accounts/bulk-delete', payload);
export const fetchGitHubAccounts = (params) => http.get('/admin/github-accounts', { params });
export const exportGitHubAccounts = () => http.get('/admin/github-accounts/export');
export const importGitHubAccounts = (payload) => http.post('/admin/github-accounts/import', payload);
export const createGitHubAccount = (payload) => http.post('/admin/github-accounts', payload);
export const updateGitHubAccount = (id, payload) => http.put(`/admin/github-accounts/${id}`, payload);
export const deleteGitHubAccount = (id) => http.delete(`/admin/github-accounts/${id}`);
export const bulkUpdateGitHubStatus = (payload) => http.post('/admin/github-accounts/bulk-status', payload);
export const bulkDeleteGitHubAccounts = (payload) => http.post('/admin/github-accounts/bulk-delete', payload);
export const bulkExportGitHubAccounts = (payload) => http.post('/admin/github-accounts/bulk-export', payload);
export const fetchGitHubHealthCheckConfig = () => http.get('/admin/github-accounts/health-check/config');
export const updateGitHubHealthCheckConfig = (payload) => http.put('/admin/github-accounts/health-check/config', payload);
export const runGitHubHealthCheck = (payload) => http.post('/admin/github-accounts/health-check/run', payload);
export const fetchDesktopClients = () => http.get('/admin/desktop-clients');
export const createDesktopClient = (payload) => http.post('/admin/desktop-clients', payload);
export const deleteDesktopClient = (id) => http.delete(`/admin/desktop-clients/${id}`);
export const fetchSyncLogs = (params) => http.get('/admin/logs/sync', { params });
export const fetchAuditLogs = (params) => http.get('/admin/logs/audit', { params });
export const fetchBatches = (params) => http.get('/admin/batches', { params });
